version: "3"
services:
  app:
    build: .
    depends_on:
      - mysql
    ports:
      - "8080:80"
    volumes:
      - .:/src/app
    links:
      - mysql

  phpMyAdmin:
    depends_on:
      - mysql
    image: "phpmyadmin/phpmyadmin:latest"
    ports:
      - "8083:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT= 3306
    links:
      - mysql


  mysql:
    image: "mysql:5.7.28"
    ports:
      - "13306:3306"
    environment:
      - MYSQL_DATABASE=docker
      - MYSQL_ROOT_PASSWORD=password
